eRIKprooviülesanne/Models/Osavotjad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRIKprooviülesanne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osavotjad
    {
        public int ID { get; set; }
        public string Eesnimi { get; set; }
        public string Perenimi { get; set; }
        public int Isikukood { get; set; }
        public string Makskmisviis { get; set; }
        public string Lisainfo { get; set; }
        public Nullable<int> Yritus_ID { get; set; }
    
        public virtual Yritus1 Yritus1 { get; set; }
    }
}

eRIKprooviülesanne/Controllers/OsavotjadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eRIKprooviülesanne.Models;
using eRIKprooviülesanne.ViewModels;

namespace eRIKprooviülesanne.Controllers
{
    public class OsavotjadsController : Controller
    {
        private YritusEntities1 db = new YritusEntities1();

        

        // GET: Osavotjads
        public async Task<ActionResult> Index()
        {
            var osavotjads = db.Osavotjads.Include(o => o.Yritus1);
            return View(await osavotjads.ToListAsync());
        }
        public async Task<ActionResult> View1()
        {
            var x = from o in db.Osavotjads join o2 
                            in db.Yritus1 on o.ID equals o2.ID
                            where o.ID.Equals(o2.ID) select new ViewModelVM { Osavotjad = o, Yritus1 = o2 };
            return View(x);
        }

        // GET: Osavotjads/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osavotjad osavotjad = await db.Osavotjads.FindAsync(id);
            if (osavotjad == null)
            {
                return HttpNotFound();
            }
            return View(osavotjad);
        }

        // GET: Osavotjads/Create
        public ActionResult Create()
        {
            ViewBag.Yritus_ID = new SelectList(db.Yritus1, "ID", "Ürituse_nimi");
            return View();
        }

        // POST: Osavotjads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Eesnimi,Perenimi,Isikukood,Makskmisviis,Lisainfo,Yritus_ID")] Osavotjad osavotjad)
        {
            if (ModelState.IsValid)
            {
                db.Osavotjads.Add(osavotjad);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Yritus_ID = new SelectList(db.Yritus1, "ID", "Ürituse_nimi", osavotjad.Yritus_ID);
            return View(osavotjad);
        }

        // GET: Osavotjads/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osavotjad osavotjad = await db.Osavotjads.FindAsync(id);
            if (osavotjad == null)
            {
                return HttpNotFound();
            }
            ViewBag.Yritus_ID = new SelectList(db.Yritus1, "ID", "Ürituse_nimi", osavotjad.Yritus_ID);
            return View(osavotjad);
        }

        // POST: Osavotjads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Eesnimi,Perenimi,Isikukood,Makskmisviis,Lisainfo,Yritus_ID")] Osavotjad osavotjad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(osavotjad).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Yritus_ID = new SelectList(db.Yritus1, "ID", "Ürituse_nimi", osavotjad.Yritus_ID);
            return View(osavotjad);
        }

        // GET: Osavotjads/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osavotjad osavotjad = await db.Osavotjads.FindAsync(id);
            if (osavotjad == null)
            {
                return HttpNotFound();
            }
            return View(osavotjad);
        }

        // POST: Osavotjads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Osavotjad osavotjad = await db.Osavotjads.FindAsync(id);
            db.Osavotjads.Remove(osavotjad);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eRIKprooviülesanne/Controllers/Yritus1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eRIKprooviülesanne.Models;

namespace eRIKprooviülesanne.Controllers
{
    public class Yritus1Controller : Controller
    {
        private YritusEntities1 db = new YritusEntities1();

        // GET: Yritus1
        public async Task<ActionResult> Index()
        {
            return View(await db.Yritus1.ToListAsync());
        }
        public async Task<ActionResult> NewIndex()
        {
            return View(await db.Yritus1.ToListAsync());
        }

        // GET: Yritus1/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            if (yritus1 == null)
            {
                return HttpNotFound();
            }
            return View(yritus1);
        }

        // GET: Yritus1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Yritus1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Ürituse_nimi,Toimumisaeg,Koht,Lisainfo")] Yritus1 yritus1)
        {
            if (ModelState.IsValid)
            {
                db.Yritus1.Add(yritus1);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(yritus1);
        }

        // GET: Yritus1/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            if (yritus1 == null)
            {
                return HttpNotFound();
            }
            return View(yritus1);
        }

        // POST: Yritus1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Ürituse_nimi,Toimumisaeg,Koht,Lisainfo")] Yritus1 yritus1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(yritus1).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(yritus1);
        }

        // GET: Yritus1/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            if (yritus1 == null)
            {
                return HttpNotFound();
            }
            return View(yritus1);
        }

        // POST: Yritus1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            db.Yritus1.Remove(yritus1);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eRIKprooviülesanne/Views/Osavotjads/Create.cshtml
@model eRIKprooviülesanne.Models.Osavotjad

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Osavotjad</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Eesnimi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eesnimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eesnimi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Perenimi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Perenimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Perenimi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Isikukood, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Isikukood, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Isikukood, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Makskmisviis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Makskmisviis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Makskmisviis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lisainfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lisainfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lisainfo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yritus_ID, "Yritus_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Yritus_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Yritus_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

eRIKprooviülesanne/Views/Osavotjads/Delete.cshtml
@model eRIKprooviülesanne.Models.Osavotjad

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Osavotjad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Eesnimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eesnimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Perenimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Perenimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Isikukood)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isikukood)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Makskmisviis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Makskmisviis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lisainfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lisainfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yritus1.Ürituse_nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yritus1.Ürituse_nimi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eRIKprooviülesanne/Views/Osavotjads/Details.cshtml
@model eRIKprooviülesanne.Models.Osavotjad

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Osavotjad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Eesnimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eesnimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Perenimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Perenimi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Isikukood)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Isikukood)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Makskmisviis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Makskmisviis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lisainfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lisainfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yritus1.Ürituse_nimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yritus1.Ürituse_nimi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

eRIKprooviülesanne/Views/Osavotjads/Edit.cshtml
@model eRIKprooviülesanne.Models.Osavotjad

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Osavotjad</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Eesnimi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eesnimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eesnimi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Perenimi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Perenimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Perenimi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Isikukood, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Isikukood, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Isikukood, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Makskmisviis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Makskmisviis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Makskmisviis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lisainfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lisainfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lisainfo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yritus_ID, "Yritus_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Yritus_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Yritus_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

eRIKprooviülesanne/Views/Osavotjads/Index.cshtml
@model IEnumerable<eRIKprooviülesanne.Models.Osavotjad>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Eesnimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Perenimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Isikukood)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Makskmisviis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lisainfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Yritus1.Ürituse_nimi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Eesnimi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Perenimi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Isikukood)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Makskmisviis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lisainfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Yritus1.Ürituse_nimi)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

eRIKprooviülesanne/Views/Osavotjads/View1.cshtml
@model IEnumerable<eRIKprooviülesanne.ViewModels.ViewModelVM>



<div class="container-fluid">

    <div class="panel panel-collapse">
        <div class="panel-heading">
            <div class="container-fluid">
                <div class="col-xs-3 text-left">
                    <h3 class="panel-title abc">
                        Osavõtjad
                    </h3>
                </div>
                <div class="col-xs-3 pull-right center-cropped ">
                    <img src="~/Pictures/libled.jpg" class="img-responsive" />
                </div>
            </div>
        </div>

        
        <div class="panel-body">
            <h4 class="text-primary">Osavõtjad</h4>
            <div>
                                  
                        
                        

                    @foreach (var item in Model)
                    {
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Yritus1.Ürituse_nimi)
                            </dt>
                            <dd>
                                @Html.DisplayFor(modelItem => item.Yritus1.Ürituse_nimi)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Yritus1.Toimumisaeg)
                            </dt>
                            <dd>
                                @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.Yritus1.Toimumisaeg))
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Yritus1.Koht)
                            </dt>
                            <dd>
                                @Html.DisplayFor(modelItem => item.Yritus1.Koht)
                            </dd>
                            <dl class="dl-horizontal">                                
                                <dd>
                                    @Html.DisplayFor(model => item.Osavotjad.Eesnimi)
                                </dd>                              
                                <dd>
                                    @Html.DisplayFor(model => item.Osavotjad.Isikukood)
                                </dd>
                                <dd>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Yritus1.ID }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.Yritus1.ID }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Yritus1.ID })
                                </dd>
                            </dl>
                        </dl>
                    }
@foreach (var item in Model)
{
                
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Osavotjad</h4>
                        
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => item.Osavotjad.Eesnimi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => item.Osavotjad.Eesnimi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => item.Osavotjad.Eesnimi, "", new { @class = "text-danger" })
                            </div>
                        </div>                        
                        <div class="form-group">
                            @Html.LabelFor(model => item.Osavotjad.Perenimi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => item.Osavotjad.Perenimi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => item.Osavotjad.Perenimi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => item.Osavotjad.Isikukood, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => item.Osavotjad.Isikukood, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => item.Osavotjad.Isikukood, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => item.Osavotjad.Makskmisviis, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => item.Osavotjad.Makskmisviis, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => item.Osavotjad.Makskmisviis, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => item.Osavotjad.Lisainfo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => item.Osavotjad.Lisainfo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => item.Osavotjad.Lisainfo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="button" onclick="location.href='@Url.Action("NewIndex", "Yritus1")'" class="btn btn-secondary">Tagasi</button>
                                <button type="submit" onclick="location.href='@Url.Action("Create", "Osavotjads")'" class="btn btn-primary">Lisa</button>
                            </div>
                        </div>
                        
                    </div>
                

                

                }
            </div>        
        </div>
    </div>
</div>