eRIKprooviülesanne/Controllers/Yritus1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eRIKprooviülesanne.Models;

namespace eRIKprooviülesanne.Controllers
{
    public class Yritus1Controller : Controller
    {
        private YritusEntities1 db = new YritusEntities1();

        // GET: Yritus1
        public async Task<ActionResult> Index()
        {
            return View(await db.Yritus1.ToListAsync());
        }
        public async Task<ActionResult> NewIndex()
        {
            return View(await db.Yritus1.ToListAsync());
        }

        // GET: Yritus1/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            if (yritus1 == null)
            {
                return HttpNotFound();
            }
            return View(yritus1);
        }

        // GET: Yritus1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Yritus1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Ürituse_nimi,Toimumisaeg,Koht,Lisainfo")] Yritus1 yritus1)
        {
            if (ModelState.IsValid)
            {
                db.Yritus1.Add(yritus1);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(yritus1);
        }

        // GET: Yritus1/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            if (yritus1 == null)
            {
                return HttpNotFound();
            }
            return View(yritus1);
        }

        // POST: Yritus1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Ürituse_nimi,Toimumisaeg,Koht,Lisainfo")] Yritus1 yritus1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(yritus1).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(yritus1);
        }

        // GET: Yritus1/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            if (yritus1 == null)
            {
                return HttpNotFound();
            }
            return View(yritus1);
        }

        // POST: Yritus1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Yritus1 yritus1 = await db.Yritus1.FindAsync(id);
            db.Yritus1.Remove(yritus1);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eRIKprooviülesanne/Controllers/YritusedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eRIKprooviülesanne.Controllers
{
    public class YritusedController : Controller
    {
        // GET: Yritused
        public ActionResult Index()
        {
            return View();
        }
    }
}

eRIKprooviülesanne/Views/Shared/OsaPart.cshtml
@model IEnumerable<eRIKprooviülesanne.Models.Osavotjad>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Eesnimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Perenimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Isikukood)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Makskmisviis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lisainfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Yritus1.Ürituse_nimi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Eesnimi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Perenimi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Isikukood)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Makskmisviis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lisainfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Yritus1.Ürituse_nimi)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

eRIKprooviülesanne/Views/Shared/View2.cshtml
@Html.Partial("YrPart")
@Html.Partial("OsaPart")

eRIKprooviülesanne/Views/Shared/YrPart.cshtml
@model IEnumerable<eRIKprooviülesanne.Models.Yritus1>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ürituse_nimi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Toimumisaeg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Koht)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lisainfo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ürituse_nimi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Toimumisaeg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Koht)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lisainfo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

eRIKprooviülesanne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Proovitöö</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="container">
    <div class="navbar navbar-inverse">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href='@Url.Action("Index", "Yritused")'>
                <img img src='@Url.Content("~/Pictures/logo.svg")' hspace="20" vspace="10" />
            </a>        
        </div>
        <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "NewIndex" ? "active" : "")">@Html.ActionLink("Avaleht", "NewIndex", "Yritus1")</li>
                <li class="@(ViewContext.RouteData.Values["Action"].ToString() == "Create" ? "active" : "")">@Html.ActionLink("Ürituste Lisamine", "Create", "Yritus1")</li>
            </ul>
            <a class="navbar-right">
                <span>
                    <img src="~/Pictures/symbol.svg" width="50" height="50" hspace="20" vspace="5" />
                </span>
            </a>
        </div>
    </div>
</div>
    <div class="container body-content">
        @RenderBody()
       
        <footer>            
            <div class="panel panel-danger">                
                <div class="panel-footer">
                    <table class="table-responsive">
                        <thead>
                            <tr>

                                <th>Erakliendi tugi</th>
                                <th>Ärikliendi tugi</th>
                                <th>Seadmetugi</th>
                                <th>Kontakt</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>

                                <td>6 666 666 E-P 07.00-23.00</td>
                                <td>6 666 666 E-P 07.00-23.00</td>
                                <td>6 666 666 E-P 07.00-23.00</td>
                                <td>Pärnu maantee 238</td>
                            </tr>
                            <tr>

                                <td>email@email.ee</td>
                                <td>email@email.ee</td>
                                <td>email@email.ee</td>
                                <td>E-L 10.00-21.00</td>
                            </tr>
                            <tr>

                                <td>6 666 665 (fax)</td>
                                <td>6 666 665 (fax)</td>
                                <td>6 666 665 (fax)</td>
                                <td>P 10.00-15.00</td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
</footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>